# Fastfile 
# Copyright@2017 Abyss

fastlane_version "2.69.2"
default_platform :ios

platform :ios do

	before_all do
	end

	UI.important("git读取配置...")
	import_from_git(
		url: 'https://github.com/RogerAbyss/AFastlane.git', 
		branch: ENV["FASTLANE_FASTFILE_VERSION"],
		path: 'fastlane/files/Fastfile'
	)

	after_all do
	end
end